name = "admin-api-gateway"
main = "layer3-business-logic.ts"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
TURSO_DATABASE_URL = "https://evenour-evenour-evenour.aws-ap-south-1.turso.io"

# Secrets (use wrangler secret put for these)
# TURSO_AUTH_TOKEN

# Routes
routes = ["admin-api-gateway.evenour-in.workers.dev/*"]
